
FROM golang:1.14-alpine as builder

RUN apk add --no-cache --update git make
RUN mkdir /build
WORKDIR /build
RUN git clone https://github.com/sebidude/webtest.git
WORKDIR /build/webtest
RUN make build-linux

FROM scratch

COPY --from=builder /build/webtest/build/linux/webtest /usr/bin/webtest
COPY content.txt /content/content.txt
USER 10001
ENTRYPOINT ["/usr/bin/webtest"]